[project]
name = "django-app"
version = "0.1.0"
description = "A sample django app for testing the custom nginx docker image"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django~=5.2.4",
    "gunicorn~=23.0.0",
]
